<?php

use yii\db\Migration;

class m180104_103627_update_source_message_table extends Migration
{
    public function up()
    {
        $this->execute("
            INSERT INTO `source_message` (`id`, `category`, `message`, `owner_id`) VALUES
            (1, 'backend_layouts', 'Панель администратора', NULL),
            (2, 'backend_layouts', 'Логин', NULL),
            (3, 'backend_layouts', 'Товары', NULL),
            (4, 'backend_layouts', 'Заказы', NULL),
            (5, 'backend_layouts', 'Клиенты', NULL),
            (6, 'backend_layouts', 'Все пользователи', NULL),
            (7, 'backend_layouts', 'Роли', NULL),
            (8, 'backend_layouts', 'Права', NULL),
            (9, 'backend_layouts', 'Акции', NULL),
            (10, 'backend_layouts', 'Купоны', NULL),
            (11, 'backend_layouts', 'Методы доставки', NULL),
            (12, 'backend_layouts', 'Методы оплаты', NULL),
            (13, 'backend_layouts', 'Почта/рассылка', NULL),
            (14, 'backend_layouts', 'Конструктор', NULL),
            (15, 'backend_layouts', 'Разметки', NULL),
            (16, 'backend_layouts', 'Шрифты', NULL),
            (17, 'backend_layouts', 'Фоны', NULL),
            (18, 'backend_layouts', 'Emoji', NULL),
            (19, 'backend_layouts', 'Цвета', NULL),
            (20, 'backend_layouts', 'Права доступа', NULL),
            (21, 'backend_layouts', 'Чехлы', NULL),
            (22, 'backend_layouts', 'Картинки', NULL),
            (23, 'backend_layouts', 'Марки товаров', NULL),
            (24, 'backend_layouts', 'Панель разработчика', NULL),
            (25, 'backend_layouts', 'Интернационализация', NULL),
            (26, 'backend_layouts', 'Языки', NULL),
            (27, 'backend_layouts', 'Исходные сообщения', NULL),
            (28, 'backend_layouts', 'Переводы', NULL),
            (29, 'backend_layouts', 'Параметры приложения', NULL),
            (30, 'backend_layouts', 'Новых заказов', NULL),
            (31, 'backend_layouts', 'Новых пользователей', NULL),
            (32, 'backend_layouts', 'Участник с', NULL),
            (33, 'backend_site', 'Статистика', NULL),
            (34, 'backend_site', 'График заказов', NULL),
            (35, 'backend_site', '7 дней', NULL),
            (36, 'backend_site', '30 дней', NULL),
            (37, 'backend_site', '365 дней', NULL),
            (38, 'backend_site', 'График заказов за 7 дней', NULL),
            (39, 'backend_site', 'График заказов за 30 дней', NULL),
            (40, 'backend_site', 'График заказов за 365 дней', NULL),
            (42, 'backend_products', 'Имя', NULL),
            (43, 'backend_products', 'Цена', NULL),
            (44, 'backend_products', 'Изображение', NULL),
            (45, 'backend_products', 'Ширина', NULL),
            (46, 'backend_products', 'Высота', NULL),
            (47, 'backend_products', 'Ширина3d', NULL),
            (48, 'backend_products', 'Высота3d', NULL),
            (49, 'backend_products', 'Статус', NULL),
            (50, 'backend_products', 'Позиция', NULL),
            (51, 'backend_form', 'Добавить', NULL),
            (52, 'backend_form', 'Расширенный поиск', NULL),
            (53, 'backend_form', 'Поиск', NULL),
            (54, 'backend_form', 'Очистить', NULL),
            (55, 'backend_form', 'Активно', NULL),
            (56, 'backend_form', 'Не активно', NULL),
            (57, 'backend_form', 'Обновить', NULL),
            (59, 'backend_products', 'Чехлы', NULL),
            (60, 'backend_products', 'Разметки', NULL),
            (61, 'backend_products', 'Цвета', NULL),
            (62, 'backend_products', 'Марки', NULL),
            (63, 'backend_products', 'Купоны', NULL),
            (64, 'backend_products', 'Добавить товар', NULL),
            (65, 'backend_products', 'Обновить товар', NULL),
            (66, 'backend_labels', 'Название', NULL),
            (67, 'backend_colors', 'Изображение', NULL),
            (68, 'backend_colors', 'Название', NULL),
            (69, 'backend_colors', 'Код цвета', NULL),
            (70, 'backend_coupons', 'Купон', NULL),
            (71, 'backend_covers', 'Изображение', NULL),
            (72, 'backend_covers', 'Имя', NULL),
            (73, 'backend_covers', 'Файл', NULL),
            (74, 'backend_covers', 'Статус', NULL),
            (75, 'backend_covers', 'Название', NULL),
            (76, 'backend_markings', 'Изображение', NULL),
            (77, 'backend_sales', 'Скидка', NULL),
            (78, 'backend_products', 'Скидки', NULL),
            (79, 'backend_form', 'Удалить', NULL),
            (80, 'backend_covers', 'Чехол', NULL),
            (81, 'backend_covers', 'Цвет', NULL),
            (82, 'backend_covers', 'Загрузить изображение', NULL),
            (83, 'backend_markings', 'Разметка', NULL),
            (84, 'backend_colors', 'Цвет', NULL),
            (85, 'backend_colors', 'Загрузить изображение', NULL),
            (86, 'backend_labels', 'Марка', NULL),
            (88, 'backend_orders', 'Доставка', NULL),
            (89, 'backend_orders', 'Оплата', NULL),
            (90, 'backend_orders', 'Купон', NULL),
            (91, 'backend_orders', 'Пользователь', NULL),
            (92, 'backend_orders', 'Сумма', NULL),
            (93, 'backend_orders', 'Коментарий', NULL),
            (94, 'backend_orders', 'Статус оплаты', NULL),
            (95, 'backend_orders', 'Статус доставки', NULL),
            (96, 'backend_orders', 'Дата', NULL),
            (97, 'backend_orders', 'Адрес доставки', NULL),
            (98, 'backend_orders', 'Товар в заказе', NULL),
            (99, 'backend_orders', 'Товар', NULL),
            (100, 'backend_orders', 'Файл', NULL),
            (101, 'backend_orders', 'Чехол', NULL),
            (102, 'backend_orders', 'Цвет', NULL),
            (103, 'backend_orders', 'Заказ', NULL),
            (104, 'backend_orders', 'Изображение', NULL),
            (105, 'backend_orders', 'Количество', NULL),
            (106, 'backend_orders', 'User Hash', NULL),
            (107, 'backend_orders', 'Ожидание оплаты', NULL),
            (108, 'backend_orders', 'Ожидание отправки', NULL),
            (109, 'backend_orders', 'Создание Заказа', NULL),
            (110, 'backend_orders', 'Оплачено', NULL),
            (111, 'backend_orders', 'Ошибка', NULL),
            (112, 'backend_orders', 'Доставлено', NULL),
            (113, 'backend_orders', 'Отправлено', NULL),
            (114, 'backend_orders', 'Товар с фото', NULL),
            (115, 'backend_form', 'Создать', NULL),
            (116, 'backend_layouts', 'Заказ', NULL),
            (117, 'backend_orders', 'Email пользователя', NULL),
            (118, 'backend_orders', 'Товары в заказе', NULL),
            (119, 'backend_orders', 'Обновить заказ', NULL),
            (120, 'backend_layouts', 'Все ользователи', NULL),
            (121, 'backend_users', 'Имя', NULL),
            (122, 'backend_users', 'Пароль', NULL),
            (123, 'backend_users', 'Password Hash', NULL),
            (124, 'backend_users', 'Password Reset Token', NULL),
            (125, 'backend_users', 'Email', NULL),
            (126, 'backend_users', 'Статус', NULL),
            (127, 'backend_users', 'Последняя активность', NULL),
            (128, 'backend_users', 'Создание', NULL),
            (129, 'backend_users', 'Обновление', NULL),
            (130, 'backend_users', 'Создать Пользователя', NULL),
            (131, 'backend_users', 'Обновить информацию о пользователе', NULL),
            (132, 'backend_users', 'Пользователь', NULL),
            (133, 'backend_coupons', 'Код', NULL),
            (134, 'backend_coupons', 'Значение', NULL),
            (135, 'backend_coupons', 'Тип дисконта', NULL),
            (136, 'backend_coupons', 'Статуст', NULL),
            (137, 'backend_coupons', 'Тип', NULL),
            (138, 'backend_roles', 'Роли пользователей', NULL),
            (139, 'backend_roles', 'Вы точно хотите удалить эту роль?', NULL),
            (140, 'backend_roles', 'Не найдено ролей', NULL),
            (141, 'backend_roles', 'Новая роль', NULL),
            (142, 'backend_roles', 'Создать новую роль', NULL),
            (143, 'backend_roles', 'Название роли', NULL),
            (144, 'backend_roles', 'Роль', NULL),
            (145, 'backend_roles', 'По умолчанию', NULL),
            (146, 'backend_roles', 'Изменить', NULL),
            (147, 'backend_roles', 'Удалить', NULL),
            (148, 'backend_roles', 'Редактировать роль', NULL),
            (149, 'backend_roles', 'Использовать эту роль по умолчанию', NULL),
            (150, 'backend_permissions', 'Права пользователей', NULL),
            (151, 'backend_permissions', 'Вы точно хотите удалить эти права?', NULL),
            (152, 'backend_permissions', 'Не найдено прав', NULL),
            (153, 'backend_permissions', 'Добавить права', NULL),
            (154, 'backend_permissions', 'Создать права', NULL),
            (155, 'backend_permissions', 'Название права пользователя', NULL),
            (156, 'backend_permissions', 'Краткое описание', NULL),
            (157, 'backend_permissions', 'Права', NULL),
            (158, 'backend_permissions', 'Описание', NULL),
            (159, 'backend_permissions', 'Изменить', NULL),
            (160, 'backend_permissions', 'Удалить', NULL),
            (161, 'backend_permissions', 'Редактировать права', NULL),
            (162, 'backend_sales', 'Значение', NULL),
            (163, 'backend_sales', 'Дата начала', NULL),
            (164, 'backend_sales', 'Дата оканчания', NULL),
            (165, 'backend_sales', 'Тип', NULL),
            (166, 'backend_sales', 'Статус', NULL),
            (167, 'backend_sales', 'Активные', NULL),
            (168, 'backend_sales', 'Не активные', NULL),
            (169, 'backend_sales', 'Чехол', NULL),
            (170, 'backend_sales', 'Марка товара', NULL),
            (171, 'backend_sales', 'Товар', NULL),
            (172, 'backend_sales', 'Акция', NULL),
            (173, 'backend_sales', 'Не активно', NULL),
            (174, 'backend_sales', 'Обновление Акции', NULL),
            (175, 'backend_sales', 'Добавление акции', NULL),
            (176, 'backend_coupons', 'Активно', NULL),
            (177, 'backend_coupons', 'Не активно', NULL),
            (178, 'backend_coupons', 'Продукт', NULL),
            (179, 'backend_coupons', 'Марки', NULL),
            (180, 'backend_coupons', 'Чехлы', NULL),
            (181, 'backend_coupons', 'Обновление купона', NULL),
            (182, 'backend_coupons', 'Название', NULL),
            (183, 'backend_coupons', 'Добавление купона', NULL),
            (184, 'backend_layouts', 'Купон', NULL),
            (185, 'backend_deliveries', 'Обновить метод доставки', NULL),
            (187, 'backend_deliveries', 'Название', NULL),
            (188, 'backend_deliveries', 'Изображение', NULL),
            (189, 'backend_deliveries', 'Описание', NULL),
            (190, 'backend_deliveries', 'Цена', NULL),
            (191, 'backend_deliveries', 'Статус', NULL),
            (192, 'backend_deliveries', 'Активно', NULL),
            (193, 'backend_deliveries', 'Не активно', NULL),
            (194, 'backend_deliveries', 'Метод доставки', NULL),
            (195, 'backend_deliveries', 'Добавить метод доставки', NULL),
            (206, 'frontend_site', 'Телефон', NULL),
            (207, 'frontend_site', 'выберите свой', NULL),
            (208, 'frontend_profile', 'Профиль', NULL),
            (209, 'frontend_profile', 'Выход', NULL),
            (210, 'frontend_profile', 'добро пожаловать', NULL),
            (211, 'frontend_profile', 'ваша информация', NULL),
            (212, 'frontend_profile', 'Ваше имя', NULL),
            (213, 'frontend_profile', 'Ваш email', NULL),
            (214, 'frontend_profile', 'Заказы', NULL),
            (215, 'frontend_profile', 'Всего потрачено', NULL),
            (216, 'frontend_profile', 'ваши адреса', NULL),
            (217, 'frontend_profile', 'ваши заказы', NULL),
            (218, 'frontend_profile', 'Заказ', NULL),
            (219, 'frontend_profile', 'оплатить сейчас', NULL),
            (220, 'frontend_button', 'конструктор', NULL),
            (221, 'frontend_profile', 'Выберите вариант оплаты', NULL),
            (222, 'frontend_site', 'Вход', NULL),
            (223, 'frontend_site', 'Аккаунт', NULL),
            (224, 'frontend_site', 'Новый пользователь?', NULL),
            (225, 'frontend_site', 'Регистрация проста и бесплатна!', NULL),
            (226, 'frontend_site', 'Быстрое оформление заказа', NULL),
            (227, 'frontend_site', 'Сохранение ваших адресов доставки', NULL),
            (228, 'frontend_site', 'Регистрация', NULL),
            (229, 'frontend_site', 'зарегистрированы?', NULL),
            (230, 'frontend_site', 'Ваше полное имя', NULL),
            (231, 'frontend_site', 'Пароль', NULL),
            (232, 'frontend_site', 'войти', NULL),
            (233, 'frontend_site', 'Закрыть', NULL),
            (234, 'frontend_site', 'создать аккаунт', NULL),
            (235, 'frontend_site', 'Email', NULL),
            (236, 'frontend_site', 'Пароль еще раз', NULL),
            (237, 'frontend_cart', 'Корзина', NULL),
            (238, 'frontend_cart', 'У вас нет товаров в корзине', NULL),
            (239, 'frontend_site', 'Профиль', NULL),
            (240, 'frontend_site', 'Случайно', NULL),
            (241, 'frontend_site', 'Очистить все', NULL),
            (242, 'frontend_site', 'Удалить', NULL),
            (243, 'frontend_site', 'Переместить слой', NULL),
            (244, 'frontend_site', 'Разметка', NULL),
            (245, 'frontend_site', 'Изображение', NULL),
            (246, 'frontend_site', 'Дизайн', NULL),
            (247, 'frontend_site', 'Загрузить из ПК', NULL),
            (248, 'frontend_site', 'Загрузить из Instagram', NULL),
            (249, 'frontend_site', 'Выбрать', NULL),
            (250, 'frontend_site', 'Поиск', NULL),
            (251, 'frontend_site', 'Ваш профиль', NULL),
            (252, 'frontend_site', 'Назад', NULL),
            (253, 'frontend_site', 'Ваша фраза', NULL),
            (254, 'frontend_site', 'Стиль шрифта', NULL),
            (255, 'frontend_site', 'Добавить текст', NULL),
            (256, 'frontend_site', 'готово', NULL),
            (257, 'frontend_site', 'Вы успешно добавили свой', NULL),
            (258, 'frontend_site', 'дизайн в корзину', NULL),
            (259, 'frontend_site', 'в корзину', NULL),
            (260, 'frontend_cart', 'товар', NULL),
            (261, 'frontend_cart', 'цена', NULL),
            (262, 'frontend_cart', 'всего', NULL),
            (263, 'frontend_cart', 'Введите промо-код', NULL),
            (264, 'frontend_cart', 'Применить', NULL),
            (265, 'frontend_cart', 'итого', NULL),
            (266, 'frontend_cart', 'оформить заказ', NULL),
            (267, 'frontend_order', 'Оформление заказа', NULL),
            (268, 'frontend_order', 'Ваше имя', NULL),
            (269, 'frontend_order', 'Телефон', NULL),
            (270, 'frontend_order', 'Адрес', NULL),
            (271, 'frontend_order', 'Варианты доставки', NULL),
            (272, 'frontend_order', 'Выберите вариант доставки', NULL),
            (273, 'frontend_order', 'Комментарий', NULL),
            (274, 'frontend_order', 'Варианты оплаты', NULL),
            (275, 'frontend_order', 'Сделайте свой выбор...', NULL),
            (276, 'frontend_order', 'Оформить заказ', NULL),
            (277, 'frontend_order', 'корзина', NULL),
            (278, 'frontend_order', 'итого', NULL),
            (279, 'frontend_order', 'Выберите вариант оплаты:', NULL),
            (280, 'frontend_order', 'Оплатить позже', NULL),
            (281, 'frontend_login', 'Неправильное имя или пароль', NULL),
            (282, 'frontend_login', 'Ваше полное имя', NULL),
            (283, 'frontend_login', 'Пароль', NULL),
            (284, 'frontend_signup', 'Это Имя уже занято', NULL),
            (285, 'frontend_signup', 'Такой email адрес уже существует!', NULL),
            (286, 'frontend_signup', 'Ваше полное имя', NULL),
            (287, 'frontend_signup', 'Введите пароль', NULL),
            (288, 'frontend_signup', 'Повторите пароль', NULL),
            (289, 'frontend_signup', 'Телефон', NULL),
            (290, 'frontend_image_upload', 'Файл не того расширения', NULL),
            (291, 'frontend_create', 'Вы не вошли в аккаунт!', NULL),
            (292, 'frontend_create', 'Неизвестный формат изображения!', NULL),
            (293, 'frontend_create', 'Введите ваш текст', NULL),
            (294, 'frontend_create', 'Сначала выберите текст', NULL),
            (295, 'frontend_create', 'Вы уверены что хотите удалить обьект?', NULL),
            (296, 'frontend_create', 'Вы уверены что хотите удалить группу обьектов?', NULL),
            (297, 'frontend_create', 'Выберите обьект', NULL),
            (298, 'frontend_create', 'Вы уверены что хотите удалить все обьекты?', NULL),
            (299, 'frontend_create', 'Ваш текст', NULL),
            (300, 'frontend_create', 'Произошла ошибка сохранения!', NULL),
            (301, 'frontend_profile', 'оплатить', NULL),
            (302, 'frontend_cart', 'Количество изменено', NULL),
            (303, 'frontend_cart', 'Произошла ошибка сохранения', NULL),
            (304, 'frontend_cart', 'Ошибка уменьшения количества! Стоит чуть подождать!', NULL),
            (305, 'frontend_cart', 'Вы дествительно хотите удалить товар из корзины?', NULL),
            (306, 'frontend_cart', 'Не удалено!', NULL),
            (307, 'frontend_cart', 'Ошибка удаления! Попробуйте позже', NULL),
            (308, 'frontend_cart', 'Купон не активен', NULL),
            (309, 'frontend_order', 'Вы не выбрали вариант доставки или оплаты!', NULL),
            (310, 'frontend_order', 'Вы не ввели адрес!', NULL),
            (311, 'frontend_order', 'Вы не ввели телефон!', NULL),
            (312, 'frontend_order', 'Заказ не найден', NULL),
            (313, 'frontend_order', 'оплатить', NULL),
            (315, 'backend_covers_name', 'Силикон', 5),
            (316, 'backend_covers_name', 'Прозрачный силикон со вставкой', 6),
            (317, 'backend_covers_name', 'Чёрный силикон со вставкой', 7),
            (318, 'backend_covers_name', 'Пластик', 8),
            (320, 'frontend_site', 'Устройство', NULL),
            (321, 'frontend_site', 'Чехол', NULL),
            (322, 'frontend_site', 'Дизайн', NULL),
            (323, 'frontend_site', 'Конструктор', NULL),
            (331, 'backend_users', 'Добавлен', NULL),
            (332, 'backend_users', 'Обновлен', NULL),
            (333, 'backend_orders', 'Адрес', NULL),
            (337, 'backend_source-langs', 'Язык', NULL),
            (338, 'backend_source-langs', 'Перевод', NULL),
            (339, 'backend_source-langs', 'Переводы', NULL),
            (341, 'backend_payments', 'Название', NULL),
            (342, 'backend_payments', 'Статус', NULL),
            (343, 'backend_payments', 'Коментарий', NULL),
            (344, 'backend_payments', 'Изображение', NULL),
            (346, 'backend_payments', 'Добавить метод оплаты', NULL),
            (347, 'backend_payments', 'Активно', NULL),
            (348, 'backend_payments', 'Не активно', NULL),
            (349, 'backend_deliveries', 'Доставка', NULL),
            (350, 'backend_deliveries', 'Купон', NULL),
            (351, 'backend_deliveries', 'Пользователь', NULL),
            (352, 'backend_payments', 'Обновить метод оплаты', NULL),
            (353, 'backend_emails', 'Сообщение', NULL),
            (354, 'backend_emails', 'Введите текст сообщения', NULL),
            (355, 'backend_emails', 'Разослать', NULL),
            (356, 'backend_labels', 'Купон', NULL),
            (357, 'backend_labels', 'Скидка', NULL),
            (358, 'backend_labels', 'Товар', NULL),
            (366, 'backend_labels', 'Добавить марку товара', NULL),
            (367, 'backend_layouts', 'Товар', NULL),
            (368, 'backend_labels', 'Обновить марку товара', NULL),
            (369, 'backend_images', 'Название', NULL),
            (370, 'backend_images', 'Имя файла', NULL),
            (371, 'backend_images', 'Расширение', NULL),
            (372, 'backend_images', 'Файл', NULL),
            (373, 'backend_images', 'Заказ и Товар', NULL),
            (374, 'backend_images', 'Товар', NULL),
            (375, 'backend_images', 'Заказ', NULL),
            (376, 'backend_ordercart', 'Товар', NULL),
            (377, 'backend_ordercart', 'Заказ', NULL),
            (378, 'backend_ordercart', 'Изображение', NULL),
            (379, 'backend_ordercart', 'Сумма', NULL),
            (380, 'backend_ordercart', 'Количество', NULL),
            (381, 'backend_ordercart', 'Чехол', NULL),
            (382, 'backend_ordercart', 'User Hash', NULL),
            (383, 'backend_ordercart', 'Цвет', NULL),
            (384, 'backend_ordercart', 'User ID', NULL),
            (385, 'backend_ordercart', 'Купон', NULL),
            (386, 'backend_images', 'Обновить изображение', NULL),
            (387, 'backend_images', 'Сумма', NULL),
            (388, 'backend_images', 'Количество', NULL),
            (389, 'backend_covers', 'Купон', NULL),
            (390, 'backend_covers', 'Скидка', NULL),
            (391, 'backend_covers', 'Товар', NULL),
            (392, 'backend_covers', 'Добавить чехол', NULL),
            (393, 'backend_covers', 'Активно', NULL),
            (394, 'backend_covers', 'Не активно', NULL),
            (395, 'backend_covers', 'Обновить чехол', NULL),
            (396, 'backend_accesses', 'Название', NULL),
            (397, 'backend_accesses', 'Значение', NULL),
            (398, 'backend_accesses', 'Пользователи', NULL),
            (399, 'backend_accesses', 'Имя', NULL),
            (400, 'backend_accesses', 'Почта', NULL),
            (401, 'backend_accesses', 'Добавление должности', NULL),
            (402, 'backend_accesses', 'Пользователь', NULL),
            (403, 'backend_accesses', 'Обновить доступ', NULL),
            (404, 'backend_markings', 'Название', NULL),
            (405, 'backend_markings', 'Имя', NULL),
            (406, 'backend_markings', 'Файл', NULL),
            (407, 'backend_markings', 'Добавить Разметку', NULL),
            (408, 'backend_markings', 'Обновить разметку', NULL),
            (409, 'backend_resources', 'Папка', NULL),
            (410, 'backend_resources', 'Имя', NULL),
            (411, 'backend_resources', 'Расширение', NULL),
            (412, 'backend_resources', 'Название', NULL),
            (413, 'backend_folders', 'Родительская папка', NULL),
            (414, 'backend_folders', 'Имя', NULL),
            (415, 'backend_folders', 'Тип', NULL),
            (418, 'backend_folders', 'Ресурсы', NULL),
            (419, 'backend_folders', 'Изображение', NULL),
            (422, 'backend_folders', 'Добавить папку', NULL),
            (423, 'backend_folders', 'Папки', NULL),
            (424, 'backend_layouts', 'Выберите тип файла', NULL),
            (425, 'backend_folders', 'Обновить папку', NULL),
            (426, 'backend_folders', 'Вы действительно хотите удалить ресурс?', NULL),
            (433, 'backend_colors', 'Добавить цвет', NULL),
            (434, 'backend_colors', 'Товар', NULL),
            (435, 'backend_colors', 'Фото', NULL),
            (436, 'backend_colors', 'Товары цвета', NULL),
            (437, 'backend_colors', 'Обновить цвет', NULL),
            (438, 'backend_languages', 'Название', NULL),
            (439, 'backend_languages', 'Статус', NULL),
            (440, 'backend_languages', 'Комментарий', NULL),
            (441, 'backend_languages', 'Изображение', NULL),
            (442, 'backend_languages', 'URL языка', NULL),
            (443, 'backend_languages', 'Добавить язык', NULL),
            (444, 'backend_languages', 'Активно', NULL),
            (445, 'backend_languages', 'Не активно', NULL),
            (446, 'backend_languages', 'Файл', NULL),
            (447, 'backend_languages', 'Обновить язык', NULL),
            (450, 'backend_source-messages', 'Категория', NULL),
            (451, 'backend_source-messages', 'Сообщение', NULL),
            (452, 'backend_source-messages', 'Поиск сообщения...', NULL),
            (453, 'backend_source-messages', 'Поиск категории...', NULL),
            (454, 'backend_source-messages', 'Статус', NULL),
            (455, 'backend_source-messages', 'Перевод', NULL),
            (456, 'backend_source-messages', 'Язык', NULL),
            (457, 'backend_source-messages', 'Редактировать', NULL),
            (458, 'backend_source-messages', 'Нет переводов', NULL),
            (459, 'backend_source-messages', 'Создать исходное сообщение', NULL),
            (460, 'backend_source-messages', 'Категория сообщения', NULL),
            (461, 'backend_source-messages', 'Исходное сообщение', NULL),
            (462, 'backend_source-messages', 'Перевод слова', NULL),
            (463, 'backend_source-messages', 'Перевести во всех категориях', NULL),
            (464, 'backend_translations', 'Исходное сообщение', NULL),
            (465, 'backend_messages', 'Язык', NULL),
            (466, 'backend_messages', 'Перевод', NULL),
            (467, 'backend_translations', 'Добавить перевод', NULL),
            (468, 'backend_translations', 'Выбрать слово для перевода', NULL),
            (469, 'backend_translations', 'Выбрать язык перевода', NULL),
            (470, 'backend_translations', 'Перевод', NULL),
            (471, 'backend_translations', 'Обновить перевод', NULL),
            (473, 'backend_settings', 'Ключ', NULL),
            (474, 'backend_settings', 'Значение', NULL),
            (475, 'backend_settings', 'Описание', NULL);
        ");
    }

    public function down()
    {
    }
}
