<?php
/**
 * Created by PhpStorm.
 * User: decadal
 * Date: 12.05.17
 * Time: 9:16
 */

namespace frontend\controllers;

use common\models\Orders;
use common\services\LiqPay;
use frontend\core\utils\OrdersUtil;
use \yii;
use frontend\core\base\FrontendController;

class LiqpayController extends FrontendController
{
    
    public function beforeAction($action)
    {
        $this->enableCsrfValidation = false;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * @return yii\web\Response
     * @throws yii\web\MethodNotAllowedHttpException
     */
    public function actionResult() {
            $data = json_decode(base64_decode($this->getRequest('post','data')),true);
            if(!$data['order_id']){
                return null;
            }
            $order = Orders::findOne($data['order_id']);
            switch ($data['status']){
                case "success":
                    $order->status_payment = Orders::PAYMENT_ACCEPTED;
                    (new OrdersUtil())->successPayment($order);
                    break;
                case "failure":
                    $order->status_payment = Orders::PAYMENT_ERROR;
                    break;
            }
            $order->save();
    }
}