<?php

namespace common\models;

use \common\models\base\Colors as BaseColors;

/**
 * This is the model class for table "colors".
 */
class Colors extends BaseColors
{
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return array_replace_recursive(parent::rules(),
	    [
            [['name', 'code'], 'required'],
            [['name', 'code'], 'string', 'max' => 255]
        ]);
    }

    public function afterFind()
    {
        $this->name = \Yii::t('backend_'.self::tableName().'_name', $this->name);

        return parent::afterFind(); // TODO: Change the autogenerated stub
    }
	
}
