<?php

namespace common\models;

use \common\models\base\Covers as BaseCovers;

/**
 * This is the model class for table "covers".
 */
class Covers extends BaseCovers
{

    const COVER_ACTIVE = 1;
    const COVER_DISABLED = 0;
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return array_replace_recursive(parent::rules(),
	    [
            [['name'], 'required'],
            [['created_by', 'updated_by', 'file_id', 'active'], 'integer'],
            [['name'], 'string', 'max' => 255]
        ]);
    }

    public function afterFind()
    {
        $this->name = \Yii::t('backend_'.self::tableName().'_name', $this->name);

        return parent::afterFind(); // TODO: Change the autogenerated stub
    }
}
