<?php

namespace backend\models;

use Yii;
use \backend\models\base\Products as BaseProducts;

/**
 * This is the model class for table "products".
 */
class Products extends BaseProducts
{

    const PROD_ACTIVE = 1;
    const PROD_DISABLED = 0;

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return array_replace_recursive(parent::rules(),
	    [
            [['price', 'created_at', 'updated_at', 'created_by', 'updated_by', 'file_id', 'wspace_width', 'wspace_height', 'wspace_width3d', 'wspace_height3d', 'active', 'position'], 'integer'],
            [['file_id'], 'required'],
            [['name'], 'string', 'max' => 255]
        ]);
    }

    public function afterFind()
    {
        $this->name = \Yii::t('backend_'.self::tableName().'_name', $this->name);

        return parent::afterFind(); // TODO: Change the autogenerated stub
    }
	
}
